---
title: "Nutritional Factors and Pediatric Allergic Trajectories"
subtitle: "BMIN503/EPID600 Final Project"
author: "Stan Gabryszewski"
format: html
editor: visual
number-sections: true
embed-resources: true
---

------------------------------------------------------------------------

## Overview {#sec-overview}

**Give a brief a description of your project and its goal(s), what data you are using to complete it, and what two faculty/staff in different fields you have spoken to about your project with a brief summary of what you learned from each person. Include a link to your final project GitHub repository.**

This project will analyze data from the National Health and Nutrition Examination Survey (NHANES) to explore links between nutritional factors and allergic diseases in the pediatric U.S. population. Using regression modeling and machine learning methods, the study will examine how dietary patterns, growth metrics, and nutritional biomarkers associate with pediatric allergic outcomes, including atopic dermatitis (AD), IgE-mediated food allergy (IgE-FA), asthma, and allergic rhinitis (AR). This analysis has the potential to identify modifiable nutritional factors that influence allergic health trajectories in childhood.

The two faculty with who I discussed this project are Dr. Robert Grundmeier (Professor of Pediatrics at CHOP and Penn, Department of Biomedical and Health Informatics) and Dr. Rich Tsui (Professor of Anesthesiology and Critical Care at CHOP and Penn, Department of Anesthesiology and Critical Care Medicine). With Dr. Grundmeier, I discussed the analytic framework for defining allergic disease cohorts within the NHANES database. With both Dr. Grundmeier and Dr. Tsui, I discussed the selection, application, validation, interpretation, and visualization of machine learning approaches that will be used to identify nutritional predictors of allergic disease risk.

GitHub repository link: [Final Project Repo](https://github.com/gabryszews/BMIN503_Final_Project)

## Introduction {#sec-introduction}

**Describe the problem addressed, its significance, and some background to motivate the problem. This should extend what is in the @sec-overview. Explain why your problem is interdisciplinary, what fields can contribute to its understanding, and incorporate background related to what you learned from meeting with faculty/staff.**

The allergic march – typically progressing from AD to IgE-FA, asthma, AR, and eventually EoE – serves as a population-level paradigm for the sequential development of allergic diseases in children. Globally, the prevalence of allergic disorders has risen sharply in recent decades, yet how environmental and heritable factors interplay to influence these outcomes remains incompletely understood. Among them, nutrition is an important and incompletely explored domain. Nutritional exposures shape immune development, epithelial barrier integrity, and microbial diversity, all of which may modulate allergic risk. A clearer understanding of how nutritional factors contribute to allergy onset and progression could inform new strategies for prevention and management. To date, few analyses have comprehensively integrated information about nutritional status (e.g. anthropometrics, dietary intake, biomarker data) and allergic outcomes within a nationally representative pediatric cohort. The extensive nutritional and health data available in the National Health and Nutrition Examination Survey (NHANES) database provide a unique opportunity to address this gap and generate data-driven hypotheses.

The questions addressed in this project are inherently multidisciplinary, spanning allergy-immunology, clinical nutrition, statistics, epidemiology, and informatics. Knowledge in allergy-immunology is needed for a clinical and immunological framework, while knowledge in clinical nutrition is needed to contextualize anthropometric and dietary data. Moreover, knowledge in epidemiology is needed for a population-level understanding of disease patterns as well as understanding of study survey design, and lastly informatics knowledge is needed for data analysis. By integrating these disciplines, this project aims to identify and interpret relationships between various nutritional factors and allergic disease risk in children. I am positioned to undertake this work, drawing on my dual clinical board certifications in allergy-immunology and clinical nutrition, my supplemental training in epidemiology, and my ongoing learning in biomedical informatics, as facilitated by my coursework and support from my mentorship team (Drs. Robert Grundmeier and Rich Tsui).

## Methods {#sec-methods}

**Describe the data used and general methodological approach used to address the problem described in the @sec-introduction. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why.**

NHANES data will be analyzed to assess associations between nutritional factors and allergic conditions in U.S. children. Weighted regression models will account for the complex national survey design to estimate relationships between specific nutrients, biomarkers, and allergic outcomes. Exploratory machine learning methods, including random forest and XGBoost, will be applied to identify nutritional variables most predictive of allergy risk. Visual outputs will include forest plots for regression estimates, ROC curves for model performance, and variable importance or SHAP plots to interpret key predictors.

## Results {#sec-results}

Describe your results and include relevant tables, plots, and code/comments used to obtain them. You may refer to the @sec-methods as needed. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.

## Conclusion

This the conclusion. The @sec-results can be invoked here.
